### ISSUE TITLE
Error encountered when 'acli new' is pulling the drupal/recommended-project .

### ISSUE THREAD

**Issue by PunitiAcquia** [acquia/acquia_cms#1001]
**Describe the bug**
While using 'acli new' to create Drupal recommended project, following error is coming : 
>  "Frontpage View Title for breadcrumb trail": "https://www.drupal.org/files/issues/2021-07-01/core_frontpage_views_title_patch.patch",

**To Reproduce**
1. Run 'acli new' on terminal.
2. Select 'drupal/recommended project'.
3. Observe the error.

**Expected behavior**
Drupal recommended project should be pulled successfully with all necessary dependencies installed. 

**Detailed error output**
1. https://github.com/acquia/acquia_cms/blob/develop/composer.json#L166 is returning an issue when using acli new .
2. 'acli new' is pulling the drupal/recommended-project and, upon pulling dependencies and trying to apply the patch, it fails with this error
<img width="1181" alt="Screenshot 2021-12-09 at 11 25 54 PM" src="https://user-images.githubusercontent.com/88032108/145450100-e5e40ba1-a4d9-470b-8973-79d5c41390d5.png">

**System information**
acli version : 1.19

**Comment by vishalkhode1** [comment]
Closing as this is already fixed.
