### ISSUE TITLE
Feature: API Dashboard

### ISSUE THREAD

**Issue by fiasco** [acquia/acquia_cms#1061]
**Priority: [must have]**
**Size: [M]**
### Goal

Provide a single page, within a Drupal application (provided in ACMS), that displays links to all important application information for a headless Drupal implementation.

### Requirements

- Display API URL(s). E.g., /jsonapi.
- Links to view/change basic settings
- API URL
- “Next JS Site role”
- Display api keys
- Obfuscated by default, button to make visible
- “Copy” button
- Link to “Key Management” page that has CRUD operations for keys
- Display path to /json API documentation
- Require https://www.drupal.org/project/openapi/
- Require https://www.drupal.org/project/openapi_ui_redoc 
- Show url to generated docs.
- Display block listing consumers: @see /admin/config/services/consumer
- Display block listing Next JS sites. @see /admin/config/services/next  
- Display block listing users with “Next JS Site” role
- Display block listing Next JS Entity Types. @see /admin/config/services/next/entity-types
- User Journey 
- Login to Drupal application as an admin
- Navigate to the dashboard via a menu link. E.g., /admin/api-dashboard
- See all the information that I need.

### Architecture

- Should be a Drupal route
- Should be constructed such that it could be easily modified (outside of code) in the future. I.e., don’t just hard code it into a build array. Use views blocks, blocks, and LB/page_manager/site studio.

**Comment by nagwani** [comment]
@fiasco Can you please close this one, I am going to create a new ticket.
