### ISSUE TITLE
Feature: Toggle Pure Headless Mode

### ISSUE THREAD

**Issue by fiasco** [acquia/acquia_cms#1062]
As a user
Who has access to admin tour dashboard page
When user chooses the option: Enable pure headless mode
And click on Save button
Then it should “turns off” superfluous frontend capabilities

### Acceptance Criteria:
- Implement the same “Disable UI” features provided by Headless Lightning:
- Drop button for Entity bundle list pages (e.g. /admin/structure/types, /admin/structure/taxonomy, /admin/structure/block) should not include link to “Manage display”.
- Tab groups when managing entity bundles should not include “Manage display” tab.
- Custom blocks should be uninstalled
- Block layout should be disabled for front-end theme
- Login should redirect to content (node) list page
- Home route should be set to API Dashboard authenticated users. Login should be shown otherwise. 
- Add “Content modeling” as a top-level admin menu item and consolidate admin links for all types of entities there rather than have them spread out across admin/structure and admin/config (specifically, user entities)
/admin/structure/display-modes route should be removed
- Remove superfluous content model (predefined entities schemas)
- Disable node view routes. E.g., node/%, etc.

### Approach:

- Implement `hook_menu_links_discovered_alter()` & `hook_local_tasks_alter()` to alter menu link/title etc. Ex:
```
function acquia_cms_headless_menu_links_discovered_alter(&$links) {
  if (ENABLED_PURE_HEADLESS_MODE) {
   foreach ($links as $key => $link) {
     if ($link['parent'] == "system.admin_reports") {
       unset($links[$key]);
     }
   }
   unset($links['system.admin_reports']);
  }
}
```
- Programmatically disable following modules:
1. block
2. block_content.

### Testing Required:
Write PHPUnit tests to make sure all hidden/disable routes don't exist & are inaccessible.

**Comment by nagwani** [comment]
@fiasco This is ready to be picked up for development.

**Comment by modularlab** [comment]
I am currently working on this ticket, fyi.

**Comment by modularlab** [comment]
FYI, I'm not sure we can disable the block module due to existing dependencies with the following modules:

- acquia_cms_common, 
- page_manager, 
- moderation_dashboard

**Comment by modularlab** [comment]
PR created: https://github.com/acquia/acquia_cms/pull/1108

**Comment by nagwani** [comment]
This is merged. Closing.
