### ISSUE TITLE
Headless - Add settings to enable robust api capabilities

### ISSUE THREAD

**Issue by nagwani** [acquia/acquia_cms#1073]
As a user
Who has access to admin tour dashboard page
When user chooses the option: Enable robust API capabilities
And click on Save button
Then it should automatically set up the Next.js site for me.

**Acceptance Criteria:**
- When user click on Save button, it should do the following automatically:
  - Create the new role (/admin/people/roles), i.e Headless and should have the following permissions:
    - Bypass content access control
    - Issue subrequests
    - View user information
  - Create the new user (/admin/people) and I should see the new user with following details:
    - Username: headless
    - Email Address: [no-reply@example.com](mailto:no-reply@example.com)
    - Roles: Headless (as created on step: 1.1).
    - Status: Active
    - Timezone: <Site Timezone>.
- When I navigate to the OAuth Settings page (/admin/config/people/simple_oauth), I should see the values for Public Key, Private Keys prefilled and public/private key files should be present at the respective directory.
- When I navigate to the Clients page (/admin/config/services/consumer), I should see the new client with following details:
  - Label: Headless Site 1.
  - Description: This client is provided by the acquia_cms_headless module.
  - User: <The user created on the step 1.2>.
  - New Secret: <Some random generated secret>.
  - Scopes: Headless (Role as created on step 1.1).
- When I navigate to Next.js site page (/admin/config/services/next) , I should see the new site with following details:
  - Label: Headless Site 1.
  - Base URL: http://localhost:3000/ (Let’s keep [this](https://git.drupalcode.org/project/consumers/-/blob/8.x-1.12/consumers.install#L16) default for now).
  - Preview URL: <Value from Base URL>/api/preview
  - Preview Secret: <Some random generated secret>.
- When I navigate to Next.JS entity types page, then I should see the following pre-configured for all the existing content types. For ex:
  - Entity Type: Content
  - Bundle: Article
  - Site Resolver: Site Selector
  - Next.JS sites: Headless Site 1. (Site created as on step 1.5).

**Approach:**
- For Step 1.1: Install Fresh Drupal 9, create the role with given steps, export the role config. Ex: user.role.headless.yml and place it inside the config/install directory. So, when the acquia_cms_headless module is installed, it’ll automatically create this role.
- For Step 1.2: On form submit do the following:
  - Before creating a user, check if the user already exists with the same username, then skip creating the user.
  - If the user doesn’t exist, programmatically create the user and assign the role created on step 1.
- For Step 1.3: For generating the oauth_keys, we can use the below service passing the directory where we need to store keys:
`\Drupal::service('simple_oauth.key.generator')->generateKeys($dir);`
- For Step 1.4:  Write a code inside hook_install() in file `acquia_cms_headless.install`:
  - Before creating a new OAuth client, check if the OAuth client already exists with the same name, then skip creating it.
  - If it doesn't exist, then programmatically create the new consumer client. @see this for reference.
- For Step 1.5: Follow similar steps as on step 2, but instead of a User entity, look for the NextSite entity.
- For Step 1.6: We’ve to programmatically configure the NextJS entity types for the content entity.
```
// This would give the list of all current content entity types.
$types = \Drupal::entityTypeManager() ->getStorage('node_type') ->loadMultiple();
// Loop through each and configure the NextJS entity type each of them.
\Drupal::entityTypeManager() ->getStorage(next_entity_type_config) ->create($values)->save();
// Before saving, please check if it already exists, then skip.

```
**Testing Required:**
Write PHPUnit tests for each of the steps added in above acceptance criteria.

**Comment by emb03** [comment]
@vishalkhode1 I am starting on this ticket and noticed the note for you to add approach, will you be doing that soon?

**Comment by nagwani** [comment]
Sorry, @vishalkhode1 has been out, we will add it tomorrow!

**Comment by nagwani** [comment]
@fiasco This is ready to be picked up for development.

**Comment by emb03** [comment]
@nagwani how does the role headless map to chapter three quiksatart, they don’t have that role

> Create the new role (/admin/people/roles), i.e Headless

**Comment by fiasco** [comment]
As discussed in our meeting last week, a consumer secret is stored encrypted in the database and cannot be retrieved to present to visitor at a later date. However, the Next.js site still needs to know (and set) the `DRUPAL_CLIENT_SECRET` environment variable. 

This process should still generate the consumer secret  but ensure it is presented to the administrator who initiates the creation sequence.

Furthermore, as a user of the ACMS wizard for headless setup, I should be able to use the wizard to reset the Next.js consumer secret.

**Comment by modularlab** [comment]
PR #1116 has been merged, fyi.

**Comment by nagwani** [comment]
Closing this one!
