### ISSUE TITLE
Headless : Add API modules to ACMS

### ISSUE THREAD

**Issue by nagwani** [acquia/acquia_cms#1082]
`As a administrator/ACMS Developer
I want to enable & use API module
So that I can display API documentation`

**Acceptance Criteria:**
Add the following Drupal modules to the ACMS repo. These should be enabled once ACMS_Headless module is enabled

- When enabling this module, it should also install & enable the following modules:
- - [OpenAPI UI](https://www.drupal.org/project/openapi_ui) module.
- - [ReDoc for OpenAPI UI](https://www.drupal.org/project/openapi_ui_redoc) module.
- - [OpenAPI JSON:API](https://www.drupal.org/project/openapi_jsonapi) module.
- Admin should be able to go into the Extend page and enable/uninstall the module. The acquia_cms_headless module should be able to install & uninstall without any errors.
- The modules should be able to install & uninstall in Latest Drupal 9 CORE with standard/minimal profile.

**Approach:**
- Add [ReDoc for OpenAPI UI](https://www.drupal.org/project/openapi_ui_redoc) module dependency on the acquia_cms root [composer.json](https://github.com/acquia/acquia_cms/blob/develop/composer.json) file and it should also be the added in composer.json file of the acquia_cms_headless module.
- Add the following patches under root composer.json file and acquia_cms_headless module’s composer.json file:
- If any patches are added for the module which exist in the composer.json file, then pin the module version (instead of using min. stability version. Ex: ‘drupal/next:^1.0’ shouldn’t be used instead ‘drupal/next:1.0.0’ should be used)

**Testing Required:**
Write PHPUnit tests to validate:
Confirm if dependent modules are enabled.
Validate path: /admin/config/services/openapi/redoc/jsonapi returns 200.

**Comment by nagwani** [comment]
@fiasco This is ready to be picked up!

**Comment by modularlab** [comment]
@nagwani This is has been merged and is ready to close.

**Comment by nagwani** [comment]
Closing this as this is merged.
