### ISSUE TITLE
Initial API setup wizard

### ISSUE THREAD

**Issue by nagwani** [acquia/acquia_cms#1098]
As an user
Who has access to admin tour dashboard page
I want to see the options for different headless option use cases
So that I can choose one of the options from given use cases.

**Acceptance Criteria:**
- When a user, who has access to the admin tour dashboard page, when they visit the tour dashboard page (/admin/tour/dashboard) should see the new wizard option with label: Headless.
- Under this wizard, I should see the dropdown having following options:
  - Enable robust API capabilities (Next.js Drupal).
  - Enable “pure headless” mode.
- There should also be buttons to Save & Ignore.

**Approach:**
- Create a new Annotation plugin i.e @AcquiaCMSTour with following details:
  - id: headless
  - label: Acquia CMS Headless
  - weight: <some_integer_value>
- You can use following file for reference: modules/acquia_cms_search/src/Plugin/AcquiaCmsTour/AcquiaConnectorForm.php

**Testing Required:**
Write PHPUnit tests (FunctionalTests) for this plugin.

**Comment by modularlab** [comment]
@nagwani Just to clarify, for this requirement:

> Under this wizard, I should see the dropdown having following options

This should actually be checkboxes, correct? This has become a one or the other selection, has it?
