### ISSUE TITLE
Disable ACMS site studio with “pure headless” mode.

### ISSUE THREAD

**Issue by nagwani** [acquia/acquia_cms#1099]
As a user
Who has access to admin tour dashboard page
When user chooses the option: Enable pure headless mode
And click on Save button
Then it should disable and uninstall all Site Studio related content/entities/modules etc.

**Acceptance Criteria:**
- When user chooses the Enable Pure headless mode, it should do the following:
  - Uninstall the Site Studio module (if it’s enabled).
  - Uninstall Acquia CMS Site studio module (if it’s enabled).
  - Delete any file/media etc. entities created by “Acquia CMS Site Studio”.

**Comment by nagwani** [comment]
@fiasco This is ready to be picked up!

**Comment by modularlab** [comment]
I am currently working on this ticket, via #1062

**Comment by fiasco** [comment]
Just a note that we won't uninstall a module as its invasive and can delete data forever. However, pure headless mode can and should render non-headless functions inert. This is largely around change of navigation and front end function.

**Comment by vishalkhode1** [comment]
Closing as this is completed.
