### ISSUE TITLE
Fatal error in redirects when too many failed login attempts

### ISSUE THREAD

**Issue by MatthieuScarset** [acquia/acquia_cms#1378]
If a user hits the limit of failed login attempts, the `uid` value is not set in the UserLoginForm which causes an assertion error in a custom submit callback from `acquia_cms_common`:

`$form['#submit'][] = '\Drupal\acquia_cms_common\RedirectHandler::submitForm';`

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of Acquia CMS:
1. Try to login with the wrong password many times until you reach the limit and get blocked
2. Exception is raised (see detailed output below)

**Expected behavior**
No errors are triggered from the custom validate/submit callbacks from `acquia_cms_common`.

**Detailed error output**

Code reference:

* https://github.com/acquia/acquia_cms/blob/develop/modules/acquia_cms_common/src/RedirectHandler.php#L105

Error output:
```
The website encountered an unexpected error. Please try again later.
AssertionError: Cannot load the "user" entity with NULL ID. in assert() (line 295 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).
assert(, 'Cannot load the "user" entity with NULL ID.') (Line: 295)
Drupal\Core\Entity\EntityStorageBase->load(NULL) (Line: 105)
Drupal\acquia_cms_common\RedirectHandler->handleRedirect(Object) (Line: 93)
Drupal\acquia_cms_common\RedirectHandler::submitForm(Array, Object)
```

**Comment by vishalkhode1** [comment]
Hi @MatthieuScarset 
Thanks for creating the issue. We'll take a look and fix it.
cc: @vipin-mittal-acquia / @nagwani

**Comment by vishalkhode1** [comment]
This is already fixed. Hence closing this.
