### ISSUE TITLE
404 page returned when redirecting from login

### ISSUE THREAD

**Issue by hmaruyama** [acquia/acquia_cms#1573]
**Describe the bug**
I'm using moderation_dashboard and acquia_cms_common module. I don't want to redirect the moderation dashboard page after login. so I unchecked `Redirect on login` Moderation Dashboard Settings page.
When login to site, redirect to non-existent route (`/user/{user}/moderation/dashboard`) so it shows 404 not found, neither Moderation dashboard page nor account page.

Likely suspicious code:
https://git.drupalcode.org/project/acquia_cms_common/-/blob/3.1.2/src/RedirectHandler.php#L124

Here is the situation:
* Using Acquia CMS Enterprise Low Code
* Enabled moderation_dashboard module and disabled `Redirect on login` checkbox at Moderation Dashboard Settings.
* Created an user with one of the following roles (please see the [related source](https://git.drupalcode.org/project/acquia_cms_common/-/blob/3.1.2/src/RedirectHandler.php#L169))
  * content_author
  * content_editor
  * content_administrator
  * administrator
* This behavior does not occur with user 1 account

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of Acquia CMS:
1. Run `composer create-project acquia/drupal-recommended-project project`
2. Run `./vendor/bin/acms acms:install`
3. Select `acquia_cms_enterprise_low_code` and then Acquia CMS installed
4. Create `testuser` user with administrator role
5. Move to Configuration > People > Moderation Dashboard (URL: /admin/config/people/moderation_dashboard)
6. Disable `Redirect on login`
7. Logout of the site
8. Login with testuser
9. Redirect `/user/{user}/moderation/dashboard` page and see 404 not found

**Expected behavior**
When disabled `Redirect on login` checkbox at Moderation Dashboard Settings, it should redirect to account page, not Moderation dashboard.

**Detailed error output**
Please provide as much detail about the error you're seeing as possible. Examples include errors present in the browser, Javascript console, Drush command error output, and server logs in Acquia Cloud.

**System information**
* Operating system type: Ubuntu (I'm using Acquia Cloud Enterprise / Cloud Classic)
* Operating system version: 16.04.7 LTS
* Drupal version: 10.0.9
* Acquia CMS Starter Kit: Acquia CMS Enterprise Low Code
* acquia/acquia-cms-starterkit version: 1.1.2
* drupal/acquia_cms_common version: 3.1.2

**Additional context**
N/A

**Comment by nagwani** [comment]
We will review this one and post our updates!

**Comment by vishalkhode1** [comment]
Closing, as this is fixed with [Acquia CMS Common](https://www.drupal.org/project/acquia_cms_common): [3.2.3](https://www.drupal.org/project/acquia_cms_common/releases/3.2.3) / [3.1.7](https://www.drupal.org/project/acquia_cms_common/releases/3.1.7).
