### ISSUE TITLE
Custom profile creation readme mentioning wrong composer vendor for acms components

### ISSUE THREAD

**Issue by joshirohit100** [acquia/acquia_cms#972]
In https://github.com/acquia/acquia_cms/tree/develop/CUSTOM_PROFILE, composer package has acquia has vendor, for example - `acquia/acquia_cms_article` but this should be `drupal/acquia_cms_article` as this is failing on composer require.

**Comment by vishalkhode1** [comment]
Closing this as we no longer maintaining the acquia_cms distribution.
